Fix undef `header` method failures
```
  NoMethodError: undefined method `header' for #<Rack::MockResponse:0x00005611e9cbc950>
  Did you mean?  headers
```

`#header` was dropped in the Rack 3.1 release (https://github.com/rack/rack/blob/main/CHANGELOG.md#removed-1), while the `#location` helper has been around since 2.x (https://github.com/rack/rack/commit/5e0b0a32be000a090e1580e19d9729e9b1b8ca69)